export enum BatchStatus {
  CREATED = 'CREATED',
  COLLECTED = 'COLLECTED',
  TESTED = 'TESTED',
  APPROVED = 'APPROVED',
  PROCESSED = 'PROCESSED',
  PACKAGED = 'PACKAGED',
  DISTRIBUTED = 'DISTRIBUTED',
  SOLD = 'SOLD'
}
