export enum Role {
  ADMIN = 'ADMIN',
  BEEKEEPER = 'BEEKEEPER',
  COLLECTION_CENTER = 'COLLECTION_CENTER',
  PROCESSOR = 'PROCESSOR',
  QUALITY_INSPECTOR = 'QUALITY_INSPECTOR',
  DISTRIBUTOR = 'DISTRIBUTOR',
  RETAILER = 'RETAILER',
  CONSUMER = 'CONSUMER'
}
